version: "3.3"
services:
  tests:
    build: .
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - RUN_INTEGRATION_TESTS
    command: "/bin/wait-for-it.sh rabbit:5672 -- bash -c \"go test -v github.com/cyverse-de/messaging | tee /dev/stderr | go-junit-report\""
  rabbit:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=/de
